// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rooaohciqkauwzmftwjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvb2FvaGNpcWthdXd6bWZ0d2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzEwNDYsImV4cCI6MjA2NzkwNzA0Nn0.4PT13Zxfq20erLpT0jazCDKFtS4iMCedfQvILHOCNZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});